import React from 'react';
import './HomePage.css'; // Create HomePage.css for styling

const HomePage = () => {
  return (
    <div className="home-container">
      <header>
        <img
          src="path/to/your/profile-image.jpg"
          alt="Profile"
          className="profile-image"
        />
        <p className="description">
          Your autogenerated description goes here. Talk about your success as an affiliate marketer and your goal to empower others.
        </p>
      </header>
      <main>
        <a href="https://www.getresponse.com?ab=mRrEx6vpTD" target="_blank" rel="noopener noreferrer">
          <button>Create a GetResponse Account</button>
        </a>
        <a href="https://groovepages.groovesell.com/a/lUXmh1zMpfMi" target="_blank" rel="noopener noreferrer">
          <button>Create a GrooveFunnels Account</button>
        </a>
      </main>
    </div>
  );
};

export default HomePage;
